### PR TITLE
Create HOW-TO-CONTRIBUTE.MD

### PR DESCRIPTION
**Pull request by janackeh**
#Updated content template

> Issue : Updated the content template

## Description
Updated the content template into a format that makes more sense for contributors

## Types of Changes
Changed the structure to help new contributors understand better how to fill out the template

### CODE REVIEW

**Review by discombobulateme — CHANGES_REQUESTED** [review]
Hi, this is really improving <3 thank you for putting so much work on it. 
Some things we should discuss with the group: 

1. Review process: if you cannot guarantee 2 weeks review, do not promise. You can make a note about tagging people to accelerate the process or  remind this is an open source project or something else, but never state something as people will expect it and rightfully reclaim it
2. You should decide an organization schema and let the contributor know where the file will live. If you decide you will follow the same Elemental Selenium schema: lib/tips/tip number - tip header convention, explain that and create the structure for people to find it. If you decide to another convention, describe it. Remember when learning how to code one of the first lessons is about describing step by step? A contributor guideline is that. Do not take for granted what your contributor know ad guide them step by step
3. Code language. People will have to add their code somewhere in the template and on the CMS. How will that make it clear to users in which language they are adding? What can they do if they can only contribute to 1 out of the Selenium x number of supported languages? Maybe after publishing in Ruby they can open an issue for people to cntribute with another language? How will they do that? Guide them through step by step. If necessary, create another issue to create a new template for it.

**Review by Roseywinter — COMMENTED** [review]
Looks good. A few thoughts:
1. For the explanation of how to add Images and Links, we might want to add a section of how to add a code snippet.
2. Maybe with the explanation of how add these elements, we can also include an example (unsure if necessary).

**Comment by daniellemadry** [comment]
I agree adding a: ** How to add a code snippet** I think would be a good addition to the template

**Review by aquaomarine — APPROVED** [review]
reviewed

**Review by Roseywinter — APPROVED** [review]
Looks great! Let's validate content and try it out. :)

**Review by discombobulateme — CHANGES_REQUESTED** [review]
1. instead of describing how to add a folder using the GUI, add a folder structure showing where to add the file 
2. Instead of asking for the contributor to create the whole structure, ask the user to add a language.md file for the language they are adding the tip for

**Review by discombobulateme — CHANGES_REQUESTED** [review]
Line 11: ask your contributor not to change the headers, as we use a structured and coherent format to fetch data
Line 14: we use Markdow files. You can link this information to a cheat list to help your contributor to properly format the markdown file (like in line 18)
- its good to have a quick most used cheatlist, but add examples to be copied/ pasted
- add size limit (1/ 2 paragraphs bla bla bla)
- typo on line 33 whicH
- typo line 36: prargraphs
-

**Review by discombobulateme — APPROVED** [review]

**Pull request merged**
