### PR TITLE
 added vue app

### PR DESCRIPTION
**Pull request by daniellemadry**
# One-line summary

> Issue : #1234 (only if appropriate)

## Description
A few sentences describing the overall goals of the pull request's
commits.

## Types of Changes
_What types of changes does your code introduce? Keep the ones that apply:_

- New feature (non-breaking change which adds functionality)
- Bug fix (non-breaking change which fixes an issue)
- Configuration change
- Refactor/improvements
- Documentation / non-code

## Tasks
_List of tasks you will do to complete the PR_
  - [ ] Created Task 1
  - [ ] Created Task 2
  - [ ] To-do Task 3

## Review
_List of tasks the reviewer must do to review the PR_
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

## Deployment Notes
These should highlight any db migrations, feature toggles, etc.

### CODE REVIEW

**Review by spider-sauce — COMMENTED** [review]
Did we decide as a group if we're going to use Typescript or not? Or was this enabled by bootstrapping the default app? I know Vue is first class citizen with regards to ts, just want to make sure we don't commit anything unnecessary.

**Comment by discombobulateme** [comment]
@spider-sauce good catch! Maybe we can use a simple setup, JS based and install what need by necessity?

**Comment by daniellemadry** [comment]
I can re-create the vue app and remove typescript and just use the standard structure that comes automatically enabled.

**Review by aquaomarine — COMMENTED** [review]
looks good

**Pull request closed without merging**
